[package]
name = "ntrip_client"
version = "0.1.0"
edition = "2021"

[dependencies]
rtcm_parser = {git="https://github.com/TonyWelte/rtcm_parser.git"}
# rtcm_parser = {path="../rtcm_parser"}
itertools = "0.10.5"
base64 = "0.21.2"
tokio = { version = "1.28.2", features = ["full"] }
deku = "0.16.0"
